sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

matrix:
  include:
    - os: linux
      env: STACK_YAML=stack.yaml
    - os: linux
      env: STACK_YAML=stack-8.2.2.yaml
    - os: osx
      env: STACK_YAML=stack.yaml
    - os: osx
      env: STACK_YAML=stack-8.2.2.yaml


# Download and unpack the stack executable
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/${TRAVIS_OS_NAME}-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --stack-yaml $STACK_YAML --no-terminal --skip-ghc-check clean
  - stack --stack-yaml $STACK_YAML --no-terminal --skip-ghc-check test --coverage --haddock --no-haddock-deps
